---
- name: "Initialisation : Création de l'utilisateur {{ non_root_user }}"
  hosts: all
  become: true

  tasks:
    - name: "création de l'utilisateur {{ non_root_user }}."
      user:
        name: "{{ non_root_user }}"
        shell: /bin/bash
        create_home: yes

    
    - name: "Ajouter la clé SSH du Master pour l'utilisateur {{ non_root_user }}"
      authorized_key:
        user: "{{ non_root_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/ansible_key.pub') }}" 

    - name: "autorisation du sudo sans mot de passe"
      copy:
        content: "{{ non_root_user }} ALL=(ALL) NOPASSWD:ALL"
        dest: "/etc/sudoers.d/{{ non_root_user }}"
        mode: '0440'
        validate: '/usr/sbin/visudo -cf %s'