---
- name: Secure sshd diectory and path
  hosts: servers
  become: true
  gather_facts: true

  tasks:

    - name: "2.1. S'assurer que le répertoire destiné à l'Include existe"
      ansible.builtin.file:
        path: /etc/ssh/sshd_config.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: "2.2. Créer le fichier de durcissement (Priorité 00 - First Match Wins)"
      ansible.builtin.copy:
        dest: /etc/ssh/sshd_config.d/00-hardening.conf
        owner: root
        group: root
        mode: '0600' # Droit en lecture/écriture root unique (exigence SSH)
        # SÉCURITÉ CRITIQUE : Teste la configuration SSH sur un fichier temporaire
        validate: /usr/sbin/sshd -t -f %s
        content: |
          # Fichier managé par Ansible - Lu en priorité par l'Include principal
          
          # Sécurisation des accès
          PasswordAuthentication no
          PermitRootLogin no
          PubkeyAuthentication yes
          MaxAuthTries 3

          # Paramètres de session et timeout (Déconnexion après 10 min d'inactivité)
          ClientAliveInterval 300
          ClientAliveCountMax 2

          # Restrictions de protocoles
          X11Forwarding no
          AllowTcpForwarding no
          MaxStartups 10:30:100

          # Chiffrement fort moderne (Normes ANSSI / CIS)
          KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512
          Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com
          MACs hmac-sha2-512-etm@openssh.com
      notify: "Recharger le service SSH"
